// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOniPVby2r_OVWJyBwISg_dw1Ig_D6g1I',
    appId: '1:401243472617:web:fc5db61d6a81fb1a962678',
    messagingSenderId: '401243472617',
    projectId: 'budgeting-app-3f26d',
    authDomain: 'budgeting-app-3f26d.firebaseapp.com',
    storageBucket: 'budgeting-app-3f26d.firebasestorage.app',
    measurementId: 'G-1BFCQDM19X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwoq-utzde9HRlDgCD6sQSPcEKEYv9tsA',
    appId: '1:401243472617:android:c540cfff6886b814962678',
    messagingSenderId: '401243472617',
    projectId: 'budgeting-app-3f26d',
    storageBucket: 'budgeting-app-3f26d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa03FNoUamJIFDjxgpBjcA4D9-kMlKCVM',
    appId: '1:401243472617:ios:ea70f26e26924d60962678',
    messagingSenderId: '401243472617',
    projectId: 'budgeting-app-3f26d',
    storageBucket: 'budgeting-app-3f26d.firebasestorage.app',
    iosBundleId: 'com.example.budgetingApp',
  );
}
